[package]
name = "AdventOfCodeRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.23.0"
strum_macros = "0.23.1"
memoize = "0.1.9"
lazy_static = "1.4.0"